# Generated by Django 4.2 on 2025-12-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='settings.category')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
